baseurl = "https://sniafas.eu"
title = "Home"
theme = "hugo-theme-cleanwhite"
languageCode = "en-us"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
googleAnalytics = ""
preserveTaxonomyNames = true
paginate = 5 #frontpage pagination
hasCJKLanguage = true

[outputs]
home = ["HTML", "RSS", "Algolia"]

[params]
  header_image = "img/k.jpg"
  SEOTitle = "Σταύρος Νιάφας | Steve Niafas Webpage"
  description = "Personal webpage"
  keyword = ""
  slogan = ""

  image_404 = "img/404-bg.jpg"
  title_404 = "Page not found :("
  omit_categories = false

  # leancloud storage for page view counter
  page_view_conter = false 
  leancloud_app_id = ""
  leancloud_app_key = ""

  # algolia site search
  algolia_search = true
  algolia_appId = ""
  algolia_indexName = ""
  algolia_apiKey = ""

  # Sidebar settings
  sidebar_about_description = "ML Engineer"
  sidebar_avatar = "/img/me.jpg"      # use absolute URL, seeing it's used in both `/` and `/about/`
  
  featured_tags = false 
  featured_condition_size = 1 

  # Follow https://github.com/zhaohuabing/disqus-php-api to set up your own disqus proxy
  disqus_proxy = ""
  disqus_site = ""

  friends = false
  bookmarks = false
  about_me = true

  # Include any custom CSS and/or JS files, url or relative to /static folder
  #custom_css = ["css/lightbox.css", "https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css", "css/main.css"]
  #custom_js = ["js/lightbox.js", "https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js", "js/main.js"]
  custom_css = ["css/custom.css"]

  [params.social]
  rss            = false 
  email          = "sniafas@gmail.com"
  twitter       = "https://twitter.com/sniafas"
  linkedin       = "https://www.linkedin.com/in/stavros-niafas-6084509a/"
  github         = "https://github.com/sniafas"
  medium        = "https://medium.com/@sniafas"
  flickr        = "https://www.flickr.com/photos/sniafas"
  researchgate  = "https://www.researchgate.net/profile/Stavros-Niafas"
  gscholar      = "https://scholar.google.com/citations?user=oITq9CMAAAAJ&hl=el"
  kaggle        = "https://www.kaggle.com/sniafas"
  [[params.bookmark_link]]
  title = "unsplash"
  href = "https://unsplash.com"
  
  # [[params.addtional_menus]]
  # title =  "Posts"
  # href =  "/post/"

[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params.algolia]
vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
params = ["categories"] 

[markup]
  [markup.tableOfContents]
    endLevel = 2
    startLevel = 1
  [markup.highlight]
    style = "dracula"
